version: "3.7"

services:
  influxdb:
    image: influxdb
    restart: always
    environment:
      - TZ="CET"
    ports:
      - 8086:8086
    volumes:
      - /data/influxdb:/var/lib/influxdb
      - /home/ladmin/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /home/ladmin/influxdb/influxdb.key:/etc/ssl/influxdb.key:ro
      - /home/ladmin/influxdb/influxdb.crt:/etc/ssl/influxdb.crt:ro
    logging:
      driver: splunk
      options:
        splunk-token: ${SPLUNK_TOKEN}
        splunk-url: ${SPLUNK_URL}
        splunk-format: raw
        tag:

  chronograf:
    image: chronograf
    ports:
      - 8888:8888
    logging:
      driver: splunk
      options:
        splunk-token: ${SPLUNK_TOKEN}
        splunk-url: ${SPLUNK_URL}
        splunk-format: raw
        tag:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel,digrich-bubblechart-panel
    logging:
      driver: splunk
      options:
        splunk-token: ${SPLUNK_TOKEN}
        splunk-url: ${SPLUNK_URL}
        splunk-format: raw
        tag:

networks:
  default:
    name: influx
